#!/usr/bin/env bash


echo -e "\033[33m"
echo "Git README Updater (gru) — Help"
echo "-----------------------------------"
echo ""
echo "A modular CLI tool to dynamically build and update README files locally or"
echo "push changes to remote Git repositories."
echo ""
echo "Core Commands"
echo ""
echo " > gru-target"
echo "  Manage local README targets and link them to remote repositories"
echo "    add <ID> [<REPO LINK> <BRANCH> <FILE>]   - Register a new target"
echo "    remove <ID>                              - Remove a target"
echo "    link <ID> [<REPO LINK> <BRANCH> <FILE>]  - Link/unlink remote file"
echo "    select [<ID>]                            - Select/unselect default target"
echo "    info <ID>                                - Show target details"
echo "    list                                     - List all targets"
echo "    selected                                 - Show selected target"
echo ""
echo " > gru-writer"
echo "  Manage section content inside README files"
echo "    write <TEXT> <ID> <SECTION> [TARGET]     - Add/update section line"
echo "    erase <ID> <SECTION> [TARGET]            - Remove a line from section"
echo "    set-placeholder <PH> <SECTION> [TARGET]  - Set fallback placeholder"
echo "    read [-s <SECTION>] [TARGET]             - View all/section content"
echo "    read-section <SECTION> [TARGET]          - Shortcut for section view"
echo ""
echo " > gru-worker"
echo "  Build and update the README using templates"
echo "    build <TEMPLATE> <OUTPUT> [TARGET]       - Build README from template"
echo "    remote-update <FILE> [-m MSG] [TARGET]   - Commit & push built README"
echo ""
echo " > Dependencies"
echo "  - jq"
echo "  - git"
echo ""
echo " > More Info: https://github.com/RedStoneMango/git-readme-updater"
echo -e "\033[0m"